version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest  # Explicitly set image name
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_LOCATION: file:/config/
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: secret
      SPRING_APPLICATION_NAME: eureka-server  # Ensure correct service name
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    volumes:
      - ./src/main/resources:/config
    networks:
      - auth_net

networks:
  auth_net:
    name: authentication-service_default
