version: '3.8'

services:
  eureka-server:
    build: .
    container_name: eureka-server
    image: eureka-service:eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_NAME: application
      SPRING_CONFIG_LOCATION: classpath:/config/
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: secret
      SPRING_APPLICATION_NAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    volumes:
      - ./src/main/resources:/config
    networks:
      - auth_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  auth_net:
    name: authentication-service_default
    driver: bridge
