# Server Configuration
server:
  port: 8761

# Eureka Server Configuration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-server
    prefer-ip-address: true

# Spring consolidated configurations
spring:
  application:
    name: eureka-server
  profiles:
    active: docker
  security:
    user:
      name: admin
      password: secret

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
